site_name: WordPress Playground
theme:
    name: readthedocs

repo_url: https://github.com/WordPress/wordpress-playground
edit_uri: blob/trunk/docs/

nav:
    - Getting Started: index.md
    - Compiling PHP to WebAssembly and using it in JavaScript: using-php-in-javascript.md
    - Running PHP apps in the browser with ServiceWorkers and Worker Threads: using-php-in-the-browser.md
    - Bundling WordPress for the browser: bundling-wordpress-for-the-browser.md
    - Running WordPress in the browser: running-wordpress-in-the-browser.md
    - Embedding WordPress Playground on other websites: embedding-wordpress-playground-on-other-websites.md
    - Implementing a live WordPress code editor: wordpress-plugin-ide.md
    - API Reference: api/index.md


# markdown_extensions:
#     - meta
#     - toc

hooks: ['docs_hooks.py']
